kind: Service
apiVersion: v1
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: inventory
    deploymentconfig: inventory
  type: ClusterIP
  sessionAffinity: None