kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  to:
    kind: Service
    name: inventory
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None